#!/usr/bin/env python
import web, subprocess
urls = (
  "/", "callMarxan"
  )

class callMarxan:
    def GET(self):
        try:
            marxan_response = subprocess.check_output("/home/ubuntu/workspace/marxan/Marxan243/MarOpt_v243_Linux64") # run marxan command
        except subprocess.CalledProcessError as e:
            return "Marxan return code: " + str(e.returncode)
        return marxan_response

app = web.application(urls, locals()) 

if __name__ == "__main__":
    app.run()